# Generated by Django 2.2 on 2020-10-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villain_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Villain_Image',
        ),
        migrations.AddField(
            model_name='villain',
            name='upload_field',
            field=models.ImageField(null=True, upload_to='user_directory_path'),
        ),
    ]
