# Generated by Django 2.2 on 2020-10-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villain_app', '0002_auto_20201009_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villain',
            name='is_like',
        ),
        migrations.RemoveField(
            model_name='villain',
            name='upload_field',
        ),
        migrations.AddField(
            model_name='villain',
            name='villain_url',
            field=models.URLField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
