# Generated by Django 2.2 on 2020-10-10 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villain_app', '0003_auto_20201010_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Villain',
        ),
    ]
